# Generated by Django 3.0.3 on 2020-04-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=30)),
                ('is_feature', models.CharField(max_length=30)),
            ],
        ),
    ]
