# Generated by Django 3.0.3 on 2020-04-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rating',
            field=models.IntegerField(max_length=30),
        ),
    ]
