# Generated by Django 3.0.3 on 2020-04-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200405_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
